"""``evolve_code`` — iterative test-feedback repair of a single tool, gated.

Run: ``python -m evolution.code.evolve_code --repo <hermes> --tool tools/foo.py
--visible-test tests/tools/test_foo_a.py --holdout-test tests/tools/test_foo_b.py``

Repairs one tool whose *visible* test currently fails, in a throwaway worktree
with an isolated venv (never the user's checkout), then runs the deploy gate
(surface freeze, file scope, the held-out split that defends against
teaching-to-the-test, and the regression floor). On a clean pass it can open a
*draft, human-review-only* PR carrying the anti-gaming evidence — it never
auto-merges. The gate is the point; the repair loop is commodity.
"""

from __future__ import annotations

import logging
import subprocess
from datetime import datetime
from pathlib import Path

import click
from rich.console import Console

from evolution.code.gate import DEFAULT_FLOOR_PATHS, run_code_gate
from evolution.code.repair import RepairEngine, build_dspy_proposer
from evolution.code.trace import build_repair_trace, containment_of, write_repair_trace
from evolution.core.sandbox import require_sandbox_or_fail
from evolution.code.worktree import WorktreeEnv, WorktreeError
from evolution.core.hermes_provider import resolve_default_lm
from evolution.core.pr_automation import create_pr
from evolution.core.quality_gate import run_benchmark_hook, write_gate_decision

console = Console()


def _format_pr_body(decision: dict, trace: dict) -> str:
    """A PR body that makes a human review *real*: the evidence the gate used,
    and an explicit caveat that the suite it verified against may be incomplete.
    """
    g = decision.get("guards", {})
    repair = decision.get("repair", {})
    lines = [
        f"## Code repair: `{decision.get('target_tool')}`",
        "",
        f"An automated test-feedback repair loop fixed this tool. "
        f"Fixed on round **{repair.get('fixed_round')}** of "
        f"{repair.get('rounds_used')}.",
        "",
        "### Gate evidence",
        f"- Visible test `{decision.get('visible_test')}`: **pass**",
        f"- Held-out test `{decision.get('holdout_test')}`: "
        f"**{'pass' if g.get('holdout', {}).get('passed') else 'FAILED'}** "
        f"(never shown to the proposer — guards against teaching-to-the-test)",
        f"- Surface freeze: **{'clean' if g.get('freeze_ok') else 'VIOLATED'}** "
        f"(no public signature/name/schema drift)",
        f"- File scope: only `{decision.get('target_tool')}` changed, no test files touched",
    ]
    # guards["floor"] has no "passed" key (see gate.py) and is None outright for an
    # oracle decision, so reading .get("passed") rendered FAILED on every run and
    # raised on oracle runs. Judge it by whether new failures appeared.
    floor = g.get("floor") or {}
    if floor:
        lines.append(
            f"- Regression floor `{floor.get('ran')}`: "
            f"**{'green' if not floor.get('new_failures') else 'FAILED'}**"
        )
    containment = trace.get("containment")
    if containment is not None:
        confined = containment.get("sandboxed")
        lines.append(
            f"- Test execution: **{'OS-confined' if confined else 'UNCONFINED'}** "
            f"({containment.get('mechanism') or containment.get('platform')}) — "
            "confinement denies writes outside the run dir and temp; it does not "
            "restrict reads or network"
        )

    full = decision.get("full_suite")
    if isinstance(full, dict):
        lines.append(
            f"- Full suite: **{'green' if full.get('passed') else 'FAILED'}** "
            f"({full.get('duration_seconds')}s)"
        )
    lines += [
        "",
        "> ⚠️ Verified against the **current** test suite, which may be incomplete. "
        "A passing gate means the change is consistent with existing tests — not "
        "that it is correct. Review the diff on its merits before merging.",
        "",
        "---",
        "Generated by agent-self-evolution `evolve_code`. Draft — review and merge or close manually.",
    ]
    return "\n".join(lines)


def _resolve_proposer(proposer_model: str | None):
    import dspy

    rlm = resolve_default_lm(role="optimizer", explicit_model=proposer_model)
    # 32000 so a whole-file rewrite + reasoning doesn't truncate on larger tools
    # (an 8000 cap silently truncated → unparseable → false "couldn't repair").
    lm = dspy.LM(rlm.model, **rlm.lm_kwargs, temperature=0.7, max_tokens=32000)
    console.print(f"  [dim]proposer model: {rlm.model}[/dim]")
    return build_dspy_proposer(lm)


@click.command()
@click.option("--repo", "repo_root", required=True,
              type=click.Path(exists=True, file_okay=False, path_type=Path),
              help="Root of the target git repository (e.g. the Hermes checkout).")
@click.option("--tool", "tool_relpath", required=True,
              help="Repo-relative path of the tool source to repair (e.g. tools/foo.py).")
@click.option("--visible-test", "visible_test", required=True,
              help="Repo-relative test path fed to the repair loop (must currently fail).")
@click.option("--holdout-test", "holdout_test", required=True,
              help="Repo-relative test path the proposer never sees; required to pass at deploy.")
@click.option("--base-ref", default=None,
              help="Git ref to repair from. Default: origin/<pr-base-branch> with "
                   "--create-pr, else the repo's current HEAD.")
@click.option("--base-python", default=None,
              help="Interpreter to base the isolated venv on (must have the target "
                   "repo's deps). Default: the repo's venv/.venv, else this interpreter.")
@click.option("--repair-rounds", default=5, type=click.IntRange(min=1),
              help="Max propose→test→feedback rounds (default 5).")
@click.option("--proposer-model", default=None,
              help="Override the proposer LM (else resolved from Hermes config).")
@click.option("--floor-path", "floor_paths", multiple=True,
              help=f"Regression-floor test path(s) run per accepted repair "
                   f"(default {list(DEFAULT_FLOOR_PATHS)}).")
@click.option("--min-retain-ratio", default=0.8, type=click.FloatRange(min=0.0, max=1.0),
              help="Reject a rewrite that shrinks the file below this fraction (default 0.8).")
@click.option("--output-dir", default=None,
              type=click.Path(file_okay=False, path_type=Path),
              help="Where to write gate_decision.json + repair_trace.json.")
@click.option("--benchmark-cmd", default=None,
              help="Full-suite floor run once at PR time (cwd is yours — cd \"$WORKTREE_PATH\"). "
                   "Receives WORKTREE_PATH, EVOLVED_PATH, RUN_DIR, TARGET_NAME, ARTIFACT_TYPE.")
@click.option("--benchmark-timeout-seconds", default=1800, type=click.IntRange(min=1),
              help="Wall-clock cap for --benchmark-cmd (default 1800s).")
@click.option("--create-pr/--no-create-pr", "create_pr_flag", default=False,
              help="On deploy, open a draft human-review PR (never auto-merges).")
@click.option("--pr-base-branch", default="main", help="PR base branch (default main).")
@click.option("--pr-branch-prefix", default="evolve-code/", help="Branch name prefix.")
@click.option("--pr-draft/--no-pr-draft", "pr_draft", default=True,
              help="Open the PR as a draft (default: draft — human review required).")
@click.option("--require-sandbox/--allow-unconfined", "require_sandbox", default=False,
              help="Refuse to run tests unless the OS can confine writes to the run "
                   "dir. Off by default because confinement is macOS-only; the posture "
                   "is recorded in repair_trace.json either way.")
@click.option("--pr-label", default="human-review",
              help="Label applied to the PR (default 'human-review'). Empty to skip.")
def main(
    repo_root: Path,
    tool_relpath: str,
    visible_test: str,
    holdout_test: str,
    base_ref: str | None,
    base_python: str | None,
    repair_rounds: int,
    proposer_model: str | None,
    floor_paths: tuple[str, ...],
    min_retain_ratio: float,
    output_dir: Path | None,
    benchmark_cmd: str | None,
    benchmark_timeout_seconds: int,
    require_sandbox: bool,
    create_pr_flag: bool,
    pr_base_branch: str,
    pr_branch_prefix: str,
    pr_draft: bool,
    pr_label: str,
) -> None:
    require_sandbox_or_fail(require_sandbox)
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
                        datefmt="%Y/%m/%d %H:%M:%S")
    floors = floor_paths or DEFAULT_FLOOR_PATHS
    if output_dir is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = Path("output") / "code" / Path(tool_relpath).stem / ts
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if base_ref is None:
        base_ref = f"origin/{pr_base_branch}" if create_pr_flag else "HEAD"
    if create_pr_flag:
        # Make origin/<base> available locally so the worktree starts exactly at
        # the PR base (keeps create_pr's branch-from-origin diff to the repair).
        # A failed fetch means the worktree would start from a stale or missing
        # base — never gate against that, so abort with the real cause.
        fetch = subprocess.run(
            ["git", "-C", str(repo_root), "fetch", "origin", pr_base_branch],
            capture_output=True, text=True, timeout=120)
        if fetch.returncode != 0:
            console.print(f"[red]✗ could not fetch origin/{pr_base_branch}:[/red] "
                          f"{fetch.stderr.strip()}")
            raise SystemExit(2)

    run_inputs = {
        "tool": tool_relpath, "visible_test": visible_test, "holdout_test": holdout_test,
        "base_ref": base_ref, "base_python": base_python, "repair_rounds": repair_rounds,
        "proposer_model": proposer_model, "floor_paths": list(floors),
        "min_retain_ratio": min_retain_ratio,
    }

    console.print(f"[bold]evolve_code[/bold] — repairing [cyan]{tool_relpath}[/cyan] "
                  f"from [dim]{base_ref}[/dim]")
    try:
        env = WorktreeEnv.create(repo_root, base_ref=base_ref, base_python=base_python,
                                 require_sandbox=require_sandbox)
    except WorktreeError as exc:
        console.print(f"[red]✗ worktree setup failed:[/red] {exc}")
        raise SystemExit(2)

    try:
        # Guard the package that actually contains the tool being repaired — not
        # a hardcoded sibling, which would prove nothing about the code measured.
        package = Path(tool_relpath).parts[0]
        env.assert_authoritative(package)
        console.print(f"  [green]✓[/green] isolated venv authoritative "
                      f"({package} resolves from worktree)")

        baseline = env.run_test(visible_test)
        if baseline.passed:
            console.print(f"[yellow]Visible test already passes at {base_ref}; "
                          f"nothing to repair.[/yellow]")
            raise SystemExit(0)
        if baseline.exit_code != 1:
            # exit 1 == tests ran and failed (a real bug to repair). Anything
            # else (5=nothing collected, 2/3/4=interrupted/internal/usage error)
            # means the visible test didn't run cleanly — repairing against it
            # would chase a phantom bug. Abort with the cause, don't proceed.
            console.print(f"[red]✗ visible test did not run cleanly "
                          f"(pytest exit {baseline.exit_code}); fix the test path/"
                          f"collection before repairing.[/red]")
            console.print(f"  [dim]{baseline.output[-800:]}[/dim]")
            raise SystemExit(2)

        proposer = _resolve_proposer(proposer_model)
        engine = RepairEngine(proposer, max_rounds=repair_rounds,
                              min_retain_ratio=min_retain_ratio)
        console.print(f"  repairing (up to {repair_rounds} rounds)…")
        result = engine.repair(env, tool_relpath, visible_test)
        console.print(f"  repair {'[green]fixed[/green]' if result.fixed else '[red]failed[/red]'}"
                      f" after {len(result.rounds)} round(s)"
                      + (f" (round {result.fixed_round})" if result.fixed else ""))

        gate = run_code_gate(
            env, tool_relpath=tool_relpath, visible_test_relpath=visible_test,
            holdout_test_relpath=holdout_test, repair_result=result,
            floor_paths=tuple(floors), min_retain_ratio=min_retain_ratio,
            run_inputs=run_inputs,
        )

        # Full-suite tier: only at deploy time, only if requested. The hook runs
        # in the user's cwd, so WORKTREE_PATH tells their command where to cd;
        # set it only for the hook's duration rather than leaking it globally.
        if gate.deploy and benchmark_cmd:
            import os
            prior = os.environ.get("WORKTREE_PATH")
            os.environ["WORKTREE_PATH"] = str(env.worktree)
            try:
                evolved_path = env.worktree / tool_relpath
                block = run_benchmark_hook(
                    benchmark_cmd, timeout_seconds=benchmark_timeout_seconds,
                    evolved_path=evolved_path, baseline_path=evolved_path,
                    output_dir=output_dir, target_name=tool_relpath, artifact_type="code",
                )
            finally:
                if prior is None:
                    os.environ.pop("WORKTREE_PATH", None)
                else:
                    os.environ["WORKTREE_PATH"] = prior
            block["is_full_suite"] = True
            gate.decision["full_suite"] = block
            if not block["passed"]:
                gate.deploy = False
                gate.decision["decision"] = "reject"
                gate.decision["downgraded_from"] = "deploy"  # gate passed; full suite didn't
                gate.decision["reason"] = "full-suite benchmark failed"

        final_diff = env.diff()
        write_gate_decision(output_dir, gate.decision)
        write_repair_trace(output_dir, build_repair_trace(
            tool=tool_relpath, visible_test=visible_test, holdout_test=holdout_test,
            result=result, final_diff=final_diff, containment=containment_of(env),
        ))
        console.print(f"  decision: [bold]{gate.decision['decision']}[/bold] — {gate.reason}")
        console.print(f"  artifacts: [dim]{output_dir}[/dim]")

        if gate.deploy and create_pr_flag and result.final_source is not None:
            _open_pr(env, tool_relpath, result.final_source, gate.decision, output_dir,
                     pr_base_branch, pr_branch_prefix, pr_draft, pr_label)
        elif gate.deploy and create_pr_flag:
            console.print("[yellow]deploy but no final source to PR (unexpected).[/yellow]")

        raise SystemExit(0 if gate.deploy else 1)
    finally:
        env.destroy()


def _open_pr(env, tool_relpath, final_source, decision, output_dir,
             pr_base_branch, pr_branch_prefix, pr_draft, pr_label) -> None:
    # Save the repaired source as the artifact create_pr copies onto a clean
    # branch-from-origin (isolating the PR diff to exactly this file).
    evolved_path = output_dir / f"evolved_{Path(tool_relpath).name}"
    evolved_path.write_text(final_source)
    trace_path = output_dir / "repair_trace.json"
    import json
    trace = json.loads(trace_path.read_text()) if trace_path.exists() else {}
    body = _format_pr_body(decision, trace)
    result = create_pr(
        source_repo_root=env.worktree,
        source_artifact_relpath=tool_relpath,
        evolved_artifact_path=evolved_path,
        artifact_name=Path(tool_relpath).stem,
        gate_decision=decision,
        metrics={},
        base_branch=pr_base_branch,
        branch_prefix=pr_branch_prefix,
        draft=pr_draft,
        allow_dirty=True,  # the worktree's dirty change IS the repair
        console=console,
        labels=[pr_label] if pr_label else None,
        body_override=body,
    )
    if result.status == "created":
        console.print(f"  [green]✓ PR opened:[/green] {result.url}")
    else:
        console.print(f"  [yellow]PR {result.status}:[/yellow] {result.reason}")


if __name__ == "__main__":
    main()
